name: Build MSI Installer

on:
  workflow_dispatch:
    inputs:
      tags:
        required: true
        description: Version name

jobs:
  packageMsi:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build distribution
        run: ./gradlew package

      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: tracker/build/compose
